### ISSUE TITLE
Question: can this run without nfc and touch sensing and if so how?

### ISSUE THREAD

**Issue by 0xN1ghtStalker** [canokeys/canokey-stm32#15]
I’m creating my own usb security key for personal experimentation with the stm32 ecosystem and I was wondering do I need the nfc antenna and touch sensing for the authentication part to work or should I rework my pcb to include button input

**Comment by dangfan** [comment]
No, you don't need NFC and touch sensing. Both of them are optional. 
First, you need to skip `nfc_init` and set `in_nfc_mode` to 0.
You also need to skip and touch related initialization and invoke `device_loop(0)` instead of `device_loop(1)` in the main function. One more thing is to return a touching state in `device_periodic_task` because several operations require touching.

**Comment by 0xN1ghtStalker** [comment]
Thank you, would i need to make significant changes to use a button?

**Comment by dangfan** [comment]
No. All you have to do is to implement the `GPIO_Touched` function (https://github.com/canokeys/canokey-stm32/blob/master/Src/device.c#L90).
